spring:
  application:
    name: gateway
  #    服务注册到eureka,需要一个application name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 是否与服务中心的发现组件进行结合,此时不再需要手动配置路由规则,而是按照微服务的服务名转发全部请求
          lower-case-service-id: true # 服务名用小写即可
      routes:
        - id: hello
          uri: http://localhost:9000
          predicates:
            - Path=/hello/**
          filters:
            - AddRequestParameter=key,value
            - AddRequestHeader=key,value
            - AddResponseHeader=resp,response
server:
  port: 8220


# 把gateway注册到注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://node1:8081/eureka/,http://node1:8082/eureka/,http://node1:8082/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
